version: "3"
services:
  app:
    container_name: medicalResearch_service
    restart: always
    build: ./
    ports:
     - "50061:50061"
    links:
      # - db    
       - mb
    networks: 
      - backend
    environment:
      - DB_CONNECTION=mongodb://medicalResearch:%3C%3D3D%40Uas8%23Wht%40%23p@142.93.223.203:27017
      - DB_NAME=medicalResearch
      - MB_CONNECTION=nats://nats_messaging:4222

  # db:
  #   container_name: mongo_db
  #   image: mongo
  #   ports:
  #    - "27017:27017"
  #   volumes:
  #    - "./data/db:/data/db"
  #   networks: 
  #     - backend
 
  mb:
    container_name: nats_messaging
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - backend
  ftontend:
    container_name: medicalresearchapp
    image: jpalaparthi/medicalresearchapp
    ports:
      - "1200:80"
    networks:
      - backend
networks:
  backend:
    driver: bridge
